import { memo, useEffect, useRef, type CSSProperties } from "react";

/**
 * Pass 175 - the Trinity range.
 *
 * Five layered ridgelines, viewBox 1440 x 600, generated by a seeded script
 * (smooth cubic curves through jittered points, centre peak tallest) so the
 * silhouette is organic rather than a row of triangles. No strokes.
 *
 * The haze gradient over the lower third dissolves the range into the page, so
 * the same SVG works on the cover, the login screen and behind the Home hero.
 */
const RIDGES = [
  "M -20 620.0 L -20 252.9 C 40.0 237.6 160.0 174.4 240.0 160.8 C 320.0 147.2 400.0 170.1 480.0 171.5 C 560.0 172.9 640.0 170.0 720.0 169.2 C 800.0 168.4 880.0 166.9 960.0 166.9 C 1040.0 166.9 1120.0 155.5 1200.0 168.9 C 1280.0 182.3 1400.0 234.1 1440.0 247.1 L 1460.0 620.0 Z",
  "M -20 620.0 L -20 338.3 C 30.0 324.7 120.0 273.9 180.0 256.7 C 240.0 239.5 300.0 236.6 360.0 235.2 C 420.0 233.8 480.0 257.4 540.0 248.1 C 600.0 238.8 660.0 196.3 720.0 179.2 C 780.0 162.1 840.0 134.0 900.0 145.7 C 960.0 157.4 1020.0 226.1 1080.0 249.3 C 1140.0 272.5 1200.0 275.1 1260.0 284.7 C 1320.0 294.3 1410.0 303.4 1440.0 307.2 L 1460.0 620.0 Z",
  "M -20 620.0 L -20 355.6 C 24.0 350.1 96.0 322.9 144.0 322.7 C 192.0 322.5 240.0 352.0 288.0 354.2 C 336.0 356.4 384.0 352.2 432.0 335.8 C 480.0 319.4 528.0 279.1 576.0 256.0 C 624.0 232.8 672.0 190.3 720.0 196.9 C 768.0 203.5 816.0 275.0 864.0 295.4 C 912.0 315.8 960.0 314.9 1008.0 319.1 C 1056.0 323.3 1104.0 322.9 1152.0 320.4 C 1200.0 317.9 1248.0 299.6 1296.0 304.0 C 1344.0 308.4 1416.0 339.5 1440.0 346.6 L 1460.0 620.0 Z",
  "M -20 620.0 L -20 429.5 C 20.0 431.7 80.0 449.1 120.0 442.5 C 160.0 435.9 200.0 391.0 240.0 390.0 C 280.0 389.0 320.0 439.2 360.0 436.6 C 400.0 434.1 440.0 396.4 480.0 374.7 C 520.0 353.0 560.0 312.2 600.0 306.6 C 640.0 301.0 680.0 326.8 720.0 341.2 C 760.0 355.6 800.0 385.3 840.0 393.1 C 880.0 400.9 920.0 393.3 960.0 388.1 C 1000.0 382.9 1040.0 358.2 1080.0 361.7 C 1120.0 365.2 1160.0 394.1 1200.0 409.0 C 1240.0 423.9 1280.0 444.4 1320.0 451.2 C 1360.0 458.0 1420.0 450.2 1440.0 450.0 L 1460.0 620.0 Z",
  "M -20 620.0 L -20 501.4 C 17.2 497.9 68.6 481.1 102.9 480.7 C 137.2 480.3 171.4 497.3 205.7 498.9 C 240.0 500.5 274.3 491.5 308.6 490.4 C 342.9 489.3 377.1 505.1 411.4 492.5 C 445.7 479.9 480.0 424.3 514.3 414.9 C 548.6 405.5 582.8 423.6 617.1 436.0 C 651.4 448.4 685.7 484.4 720.0 489.4 C 754.3 494.4 788.6 475.1 822.9 465.9 C 857.2 456.7 891.4 433.8 925.7 434.4 C 960.0 435.0 994.3 455.4 1028.6 469.5 C 1062.9 483.6 1097.1 512.8 1131.4 518.9 C 1165.7 525.0 1200.0 509.6 1234.3 506.2 C 1268.6 502.8 1302.8 494.9 1337.1 498.3 C 1371.4 501.7 1422.8 522.0 1440.0 526.8 L 1460.0 620.0 Z",
];

interface MountainRangeProps {
  className?: string;
  /** 0 to 1. The faint version behind the Home hero uses 0.3. */
  opacity?: number;
  animate?: boolean;
  pointerParallax?: boolean;
}

/**
 * The range fills its container width and is bottom aligned. On a 390px phone
 * the SVG keeps its aspect and is scaled with preserveAspectRatio "xMidYMax
 * slice", so the outer ridges crop away and the tall centre peak stays in view.
 */
function MountainRangeBase({ className, opacity = 1, animate = false, pointerParallax = false }: MountainRangeProps) {
  const svgRef = useRef<SVGSVGElement | null>(null);

  useEffect(() => {
    if (!pointerParallax || window.matchMedia('(prefers-reduced-motion: reduce)').matches || window.matchMedia('(hover: none)').matches) return;
    const svg = svgRef.current;
    if (!svg) return;
    let targetX = 0;
    let targetY = 0;
    let x = 0;
    let y = 0;
    let frame = 0;
    const move = (event: PointerEvent) => {
      targetX = (event.clientX / window.innerWidth - 0.5) * 2;
      targetY = (event.clientY / window.innerHeight - 0.5) * 2;
    };
    const tick = () => {
      x += (targetX - x) * 0.08;
      y += (targetY - y) * 0.08;
      for (let depth = 1; depth <= RIDGES.length; depth += 1) {
        svg.style.setProperty(`--range-x-${depth}`, `${(x * depth * 1.2).toFixed(3)}px`);
        svg.style.setProperty(`--range-y-${depth}`, `${(y * depth * 1.2).toFixed(3)}px`);
      }
      frame = requestAnimationFrame(tick);
    };
    window.addEventListener('pointermove', move, { passive: true });
    frame = requestAnimationFrame(tick);
    return () => {
      window.removeEventListener('pointermove', move);
      cancelAnimationFrame(frame);
    };
  }, [pointerParallax]);

  return (
    <svg
      ref={svgRef}
      viewBox="0 0 1440 600"
      preserveAspectRatio="xMidYMax slice"
      aria-hidden="true"
      focusable="false"
      className={`${className ?? ''} ${animate ? 'mountain-settle' : ''} ${pointerParallax ? 'mountain-pointer' : ''}`}
      style={{ display: "block", width: "100%", height: "100%", opacity }}
    >
      <defs>
        <linearGradient id="trnty-haze" x1="0" y1="0.62" x2="0" y2="1">
          <stop offset="0%" stopColor="hsl(var(--background))" stopOpacity="0" />
          <stop offset="100%" stopColor="hsl(var(--background))" stopOpacity="1" />
        </linearGradient>
      </defs>
      {RIDGES.map((d, i) => (
        <path key={i} className="mountain-layer" d={d} fill={`var(--range-${i + 1})`} style={{ '--range-depth': i + 1 } as CSSProperties} />
      ))}
      <rect x="0" y="370" width="1440" height="230" fill="url(#trnty-haze)" />
    </svg>
  );
}

export const MountainRange = memo(MountainRangeBase);
export default MountainRange;
