import { useState, useEffect, useRef } from 'react';
import { Target, Plus, Square, CheckCircle, AlertTriangle, BookOpen, Phone, ClipboardList, Video } from 'lucide-react';
import { cn } from '@/lib/utils';
import { useAuth } from '@/hooks/useAuth';
import { useNavigate } from 'react-router-dom';

interface ChecklistItem {
  id: string;
  text: string;
  completed: boolean;
  isRolledOver: boolean;
  isAutoGenerated: boolean;
  createdAt: string;
  link?: string;
}

const STORAGE_KEY = 'summit_daily_warplan';

// Simplified daily missions — clear, actionable
const DAILY_MISSIONS: (Omit<ChecklistItem, 'id' | 'completed' | 'isRolledOver' | 'createdAt'>)[] = [
  { text: 'Complete 1 training lesson', isAutoGenerated: true, link: '/app/training' },
  { text: 'Watch a training video', isAutoGenerated: true, link: '/app/training/training-videos' },
  { text: 'Attend scheduled call', isAutoGenerated: true, link: '/app/calendar' },
  { text: 'Submit required form', isAutoGenerated: true, link: '/app/forms' },
];

export function DailyChecklist() {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [items, setItems] = useState<ChecklistItem[]>([]);
  const [newItemText, setNewItemText] = useState('');
  const newItemInputRef = useRef<HTMLInputElement>(null);

  // Check if it's past 6PM PST
  const now = new Date(new Date().toLocaleString('en-US', { timeZone: 'America/Los_Angeles' }));
  const isPast6PM = now.getHours() >= 18;

  useEffect(() => {
    if (!user) return;

    const stored = localStorage.getItem(`${STORAGE_KEY}_${user.id}`);
    if (stored) {
      try {
        const parsed = JSON.parse(stored);
        const today = new Date().toDateString();

        if (parsed.date === today) {
          setItems(parsed.items || []);
        } else {
          // New day — roll over incomplete custom tasks, add fresh missions
          const incompleteItems = (parsed.items || [])
            .filter((item: ChecklistItem) => !item.completed && !item.isAutoGenerated)
            .map((item: ChecklistItem) => ({ ...item, isRolledOver: true }));

          const freshMissions = DAILY_MISSIONS.map(m => ({
            ...m,
            id: crypto.randomUUID(),
            completed: false,
            isRolledOver: false,
            createdAt: new Date().toISOString(),
          }));

          const allItems = [...freshMissions, ...incompleteItems];
          setItems(allItems);
          saveItems(allItems);
        }
      } catch {
        seedMissions();
      }
    } else {
      seedMissions();
    }
  }, [user]);

  const seedMissions = () => {
    const freshMissions = DAILY_MISSIONS.map(m => ({
      ...m,
      id: crypto.randomUUID(),
      completed: false,
      isRolledOver: false,
      createdAt: new Date().toISOString(),
    }));
    setItems(freshMissions);
    saveItems(freshMissions);
  };

  const saveItems = (newItems: ChecklistItem[]) => {
    if (!user) return;
    localStorage.setItem(`${STORAGE_KEY}_${user.id}`, JSON.stringify({
      date: new Date().toDateString(),
      items: newItems,
    }));
  };

  const addItem = (text: string) => {
    if (!text.trim()) return;
    const newItem: ChecklistItem = {
      id: crypto.randomUUID(),
      text: text.trim(),
      completed: false,
      isRolledOver: false,
      isAutoGenerated: false,
      createdAt: new Date().toISOString(),
    };
    const newItems = [...items, newItem];
    setItems(newItems);
    saveItems(newItems);
    setNewItemText('');
  };

  const toggleItem = (id: string) => {
    const newItems = items.map(item =>
      item.id === id ? { ...item, completed: !item.completed, isRolledOver: false } : item
    );
    setItems(newItems);
    saveItems(newItems);
  };

  const updateItemText = (id: string, text: string) => {
    const newItems = items.map(item =>
      item.id === id ? { ...item, text } : item
    );
    setItems(newItems);
    saveItems(newItems);
  };

  const removeItem = (id: string) => {
    const newItems = items.filter(item => item.id !== id);
    setItems(newItems);
    saveItems(newItems);
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>, id?: string) => {
    if (e.key === 'Enter') {
      e.preventDefault();
      if (id) {
        setTimeout(() => newItemInputRef.current?.focus(), 0);
      } else {
        addItem(newItemText);
      }
    }
  };

  const getIcon = (item: ChecklistItem) => {
    const t = item.text.toLowerCase();
    if (t.includes('training') || t.includes('lesson')) return <BookOpen className="w-3.5 h-3.5" />;
    if (t.includes('call') || t.includes('attend')) return <Phone className="w-3.5 h-3.5" />;
    if (t.includes('form') || t.includes('submit')) return <ClipboardList className="w-3.5 h-3.5" />;
    if (t.includes('video') || t.includes('watch')) return <Video className="w-3.5 h-3.5" />;
    return null;
  };

  const activeItems = items.filter(i => !i.completed);
  const completedCount = items.filter(i => i.completed).length;
  const totalCount = items.length;
  const completionPct = totalCount > 0 ? Math.round((completedCount / totalCount) * 100) : 0;
  const noTasksCompleted = completedCount === 0;
  const showUrgencyPulse = isPast6PM && noTasksCompleted;

  return (
    <div className={cn(
      "bg-card rounded-xl border overflow-hidden transition-all",
      showUrgencyPulse
        ? "border-destructive/50 shadow-[0_0_20px_-5px_hsl(var(--destructive)/0.3)] animate-pulse"
        : "border-border/50"
    )}>
      {/* Header */}
      <div className="p-4 border-b border-border/30">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="p-1.5 rounded-lg bg-primary/10">
              <Target className="w-4 h-4 text-primary" />
            </div>
            <div>
              <h2 className="font-bold text-sm text-foreground">Today's Tasks</h2>
              <p className="text-[10px] text-muted-foreground">Complete these before end of day</p>
            </div>
          </div>
          <span className={cn(
            "text-xs font-bold tabular-nums",
            completionPct === 100 ? "text-success" : completionPct >= 50 ? "text-primary" : "text-muted-foreground"
          )}>
            {completedCount}/{totalCount}
          </span>
        </div>

        {/* Progress bar */}
        <div className="mt-3 h-1.5 bg-muted rounded-full overflow-hidden">
          <div
            className={cn(
              "h-full rounded-full transition-all duration-500",
              completionPct === 100 ? "bg-success" : completionPct >= 50 ? "bg-primary" : "bg-muted-foreground/40"
            )}
            style={{ width: `${completionPct}%` }}
          />
        </div>
      </div>

      {/* Urgency Warning */}
      {showUrgencyPulse && (
        <div className="px-4 py-2.5 bg-destructive/10 border-b border-destructive/20 flex items-center gap-2">
          <AlertTriangle className="w-4 h-4 text-destructive" />
          <p className="text-xs font-bold text-destructive">No tasks completed — time is running out!</p>
        </div>
      )}

      <div className="p-3 space-y-1">
        {/* Active items */}
        {activeItems.map((item) => {
          const icon = getIcon(item);
          return (
            <div
              key={item.id}
              className={cn(
                "flex items-start gap-2.5 p-2.5 rounded-lg transition-all group hover:bg-muted/30",
                item.isRolledOver && "bg-primary/5 border border-primary/15"
              )}
            >
              <button
                onClick={() => toggleItem(item.id)}
                className="flex-shrink-0 mt-0.5 transition-transform hover:scale-110"
              >
                <Square className="w-4 h-4 text-muted-foreground/60 hover:text-primary transition-colors" />
              </button>
              {icon && <span className="mt-0.5 flex-shrink-0 text-muted-foreground/40">{icon}</span>}
              {item.isAutoGenerated && item.link ? (
                <button
                  onClick={() => navigate(item.link!)}
                  className="flex-1 text-left text-sm text-foreground truncate hover:underline hover:text-primary transition-colors"
                >
                  {item.text}
                </button>
              ) : (
                <input
                  type="text"
                  value={item.text}
                  onChange={(e) => updateItemText(item.id, e.target.value)}
                  onKeyDown={(e) => handleKeyDown(e, item.id)}
                  onBlur={() => { if (!item.text.trim() && !item.isAutoGenerated) removeItem(item.id); }}
                  className="flex-1 bg-transparent text-sm border-none outline-none placeholder:text-muted-foreground/50 text-foreground"
                  readOnly={item.isAutoGenerated}
                />
              )}
              {item.isRolledOver && (
                <span className="text-[9px] text-primary/80 font-bold px-1.5 py-0.5 rounded bg-primary/10 uppercase tracking-wider">
                  Yesterday
                </span>
              )}
            </div>
          );
        })}

        {/* Completed items (collapsed) */}
        {completedCount > 0 && (
          <div className="pt-1 border-t border-border/20 mt-2">
            <p className="text-[10px] text-success/60 font-medium mb-1 flex items-center gap-1">
              <CheckCircle className="w-3 h-3" />
              {completedCount} completed
            </p>
          </div>
        )}

        {/* Add custom task */}
        <div className="flex items-center gap-2.5 p-2.5 rounded-lg hover:bg-muted/30 transition-colors border border-dashed border-border/30">
          <Plus className="w-4 h-4 text-muted-foreground flex-shrink-0" />
          <input
            ref={newItemInputRef}
            type="text"
            value={newItemText}
            onChange={(e) => setNewItemText(e.target.value)}
            onKeyDown={(e) => handleKeyDown(e)}
            placeholder="Add a task..."
            className="flex-1 bg-transparent text-sm border-none outline-none placeholder:text-muted-foreground/40"
          />
        </div>
      </div>
    </div>
  );
}
